### ISSUE TITLE
Replace winapi crate with windows-sys

### ISSUE THREAD

**Issue by kgrech** [nushell/nu-ansi-term#14]
Depending on [winapi](https://github.com/retep998/winapi-rs) crate is not the best idea:
- It is not maintained
- The source code of it contains large number of precompiled binaries (see [here](https://github.com/retep998/winapi-rs/tree/0.3/x86_64/lib)). It is not clear how were they build, what is the license of them and what binary code they contain
- There is [an official](https://crates.io/crates/windows) alternative windows crate supported by Microsoft.
- Other projects are migrating already (e.g. [socket2](https://github.com/rust-lang/socket2/pull/303), [remove-dir-all](https://github.com/XAMPPRocky/remove_dir_all/pull/42), [mio](https://github.com/tokio-rs/mio/pull/1556) and also parking_lot, wasmtime, and others)

Would you consider the migration?

**Comment by fdncred** [comment]
> Would you consider the migration?

Yes, probably so. Although my initial concern would be increased compile time or increased dependencies. I'm familiar with Microsoft's crate and agree it's probably the direction we should go. I'm just hoping it's a change for the better.

**Comment by Sytten** [comment]
At this point most people are already using the official windows-sys crate anyway since a lot of projects moved to it, so I would say not to worry too much about compile time or increased dependencies.

**Comment by fdncred** [comment]
LOL. Just don't worry about it. :) 

One of the problems is that the windows crate is moving very fast. So, that means lots of versions. I also agree that people are migrating to it like they should. The problem comes in where we have 10 versions of the windows crates because people don't keep their projects up to date. That's especially a problem in crates like this one that don't get updated very frequently. i.e. It'll get behind fast.  But that's the age-old story with crates.

Having said all that, like I said before, we'd probably accept a PR to move to the windows crate.

**Comment by kgrech** [comment]
> Having said all that, like I said before, we'd probably accept a PR to move to the windows crate.

I am happy to contribute it then

**Comment by sholderbach** [comment]
Thanks for picking that up and moving the ecossystem forward @kgrech!
