### ISSUE TITLE
No changelog?

### ISSUE THREAD

**Issue by hawkw** [nushell/nu-ansi-term#7]
As far as I can tell, this crate doesn't appear to have a changelog, and the Git tags visible on GitHub are all for very old versions (and apparently from the ogham/ansi-term repo). Is there a changelog available for this crate, and if not, would the maintainers consider adding one?

**Comment by sholderbach** [comment]
Sorry that we didn't tag the new versions. The changelog will probably take some archeology work. This fork lived for a while inside the main [nushell tree](https://github.com/nushell/nushell) as a crate inside the workspace. So a series of version bumps was actually meaningless and only due to regular nushell releases. @fdncred we should probably get around and document our changes properly, for other projects to use the crate in lieu of updates to the source repository.

**Comment by fdncred** [comment]
Ugh, documentation. LOL.  Agreed, it will take digging throught the commit log to generate a change log. I originally added this crate to have an easier way to access "Bright" ansi colors, but there have been a few more changes since then.

**Comment by jaudiger** [comment]
Should we close this issue? Now this [PR](https://github.com/nushell/nu-ansi-term/pull/25) has been merged? Or is there any other pending tasks to be done?

**Comment by fdncred** [comment]
Good idea.
